name: 入札案件自動収集

on:
  schedule:
    - cron: '0 23 * * *'  # 毎日朝8時JST
    - cron: '0 9 * * *'   # 毎日夕方6時JST
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'テストモード'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  collect-bids:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-minimal.txt

    - name: Create necessary directories
      run: |
        mkdir -p logs
        mkdir -p data

    - name: Download previous database
      continue-on-error: true
      run: |
        if [ -f data/bids.db ]; then
          echo "Database already exists"
        else
          echo "No previous database found"
          touch data/bids.db
        fi

    - name: Run bid collection
      env:
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        TEST_MODE: ${{ github.event.inputs.test_mode || 'false' }}
      run: |
        python src/main.py

    - name: Generate dashboard
      run: |
        python src/web/dashboard_generator.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: bid-collection-results
        path: |
          data/
          logs/
          docs/dashboard_data.json
        retention-days: 30

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: actions/deploy-pages@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
